http:
  middlewares:
    redirect-www-to-apex:
      redirectRegex:
        regex: '^https?://www\.stellartail\.cn/(.*)'
        replacement: "https://stellartail.cn/${1}"
        permanent: true
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: strict-origin-when-cross-origin
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
