export {
  addGearTagViews,
  buildGearAtlasPayload,
  buildGearPayload,
  combineSpecValue,
  createDefaultGearFormData,
  createGearTagSuggestionViews,
  gearToFormData,
  getGearSpecFieldViews,
  GEAR_CATEGORY_OPTIONS,
  GEAR_CURRENCY_OPTIONS,
  GEAR_STATUS_OPTIONS,
  GEAR_TAG_COLOR_OPTIONS,
  GEAR_WEIGHT_UNIT_OPTIONS,
  normalizeGearTagColor,
  optionIndex,
  PURCHASE_LOCATION_OPTIONS,
  randomGearTagColor,
  type GearCategory,
  type GearCurrency,
  type GearFormData,
  type GearStatus,
  type GearTagColor,
  type GearTagSuggestionView,
  type GearTagView,
  type GearWeightUnit,
} from "./gear-utils";
