package com.rustella.stellartrail.ui.theme

import androidx.compose.ui.graphics.Color

data class StellarTrailPalette(
    val pageBackground: Color,
    val surface: Color,
    val surfaceStrong: Color,
    val controlBackground: Color,
    val border: Color,
    val softBorder: Color,
    val textPrimary: Color,
    val textMuted: Color,
    val headingMuted: Color,
    val accent: Color,
    val brand: Color,
    val brandText: Color,
    val brandSoft: Color,
    val brandSoftText: Color,
    val softControlBackground: Color,
    val softControlText: Color,
    val chipBackground: Color,
    val topBarBackground: Color,
    val footerBackground: Color,
    val heroStart: Color,
    val heroMid: Color,
    val heroEnd: Color,
    val heroHill: Color,
    val heroSun: Color,
    val heroStar: Color,
    val heroStarAccent: Color,
    val successText: Color,
    val successBackground: Color,
    val warningText: Color,
    val warningBackground: Color,
    val dangerText: Color,
    val dangerBackground: Color,
    val infoText: Color,
    val infoBackground: Color,
)

object StellarTrailDesignColors {
    val Light = StellarTrailPalette(
        pageBackground = Color(0xFFF8FAFC),
        surface = Color(0xFFFFFFFF),
        surfaceStrong = Color(0xFFFFFFFF),
        controlBackground = Color(0xFFF8FAFC),
        border = Color(0xFFE2E8F0),
        softBorder = Color(0xFFF1F5F9),
        textPrimary = Color(0xFF0F172A),
        textMuted = Color(0xFF64748B),
        headingMuted = Color(0xFF334155),
        accent = Color(0xFF0F766E),
        brand = Color(0xFF0F766E),
        brandText = Color(0xFFFFFFFF),
        brandSoft = Color(0xFFCCFBF1),
        brandSoftText = Color(0xFF0F766E),
        softControlBackground = Color(0xFFE2E8F0),
        softControlText = Color(0xFF475569),
        chipBackground = Color(0xFFECFDF5),
        topBarBackground = Color(0xFFF8FAFC),
        footerBackground = Color(0xFFFFFFFF),
        heroStart = Color(0xFFFFF7ED),
        heroMid = Color(0xFFECFEFF),
        heroEnd = Color(0xFFEEF2FF),
        heroHill = Color(0xFFD8F1F6),
        heroSun = Color(0xFFFBBF24),
        heroStar = Color(0xFFFFFFFF),
        heroStarAccent = Color(0xFFFBBF24),
        successText = Color(0xFF047857),
        successBackground = Color(0xFFD1FAE5),
        warningText = Color(0xFFB45309),
        warningBackground = Color(0xFFFEF3C7),
        dangerText = Color(0xFFDC2626),
        dangerBackground = Color(0xFFFFF1F2),
        infoText = Color(0xFF2563EB),
        infoBackground = Color(0xFFEFF6FF),
    )

    val Dark = StellarTrailPalette(
        pageBackground = Color(0xFF120A2A),
        surface = Color(0xFF1A1035),
        surfaceStrong = Color(0xFF211343),
        controlBackground = Color(0xFF130B2A),
        border = Color(0xFF3A2465),
        softBorder = Color(0xFF2D1F4D),
        textPrimary = Color(0xFFF4EFFF),
        textMuted = Color(0xFFC7B7EB),
        headingMuted = Color(0xFFEDE7FF),
        accent = Color(0xFFC16CFF),
        brand = Color(0xFFA985FF),
        brandText = Color(0xFF241047),
        brandSoft = Color(0xFF2B1854),
        brandSoftText = Color(0xFFEDE7FF),
        softControlBackground = Color(0xFF2B1854),
        softControlText = Color(0xFFEDE7FF),
        chipBackground = Color(0xFF2B1854),
        topBarBackground = Color(0xFF120A2A),
        footerBackground = Color(0xFF100823),
        heroStart = Color(0xFF4C2C9A),
        heroMid = Color(0xFF3156B8),
        heroEnd = Color(0xFF167C7B),
        heroHill = Color(0xFF283978),
        heroSun = Color(0xFFFFCC4D),
        heroStar = Color(0xFFEFEAFF),
        heroStarAccent = Color(0xFFFFCC4D),
        successText = Color(0xFFBBF7D0),
        successBackground = Color(0xFF123522),
        warningText = Color(0xFFFFD66B),
        warningBackground = Color(0xFF4B3608),
        dangerText = Color(0xFFFECDD3),
        dangerBackground = Color(0xFF3B1520),
        infoText = Color(0xFFBFDBFE),
        infoBackground = Color(0xFF1A274D),
    )
}

val TrailPrimary = StellarTrailDesignColors.Light.brand
val TrailPrimaryDark = StellarTrailDesignColors.Dark.brand
val TrailSecondary = StellarTrailDesignColors.Light.infoText
val TrailSecondaryDark = StellarTrailDesignColors.Dark.infoText
val TrailTertiary = Color(0xFFF97316)
val TrailSurface = StellarTrailDesignColors.Light.pageBackground
val TrailSurfaceDark = StellarTrailDesignColors.Dark.pageBackground
